version: "1.0"
services:
  valkey:
    image: valkey/valkey
    container_name: C-Valkey
    restart: always
    ports:
      - 6380:6379
  
  memcached:
    image: memcached
    container_name: C-Memcached
    restart: always
    ports:
      - 11211:11211
  
  redis:
    image: redis
    container_name: C-Redis
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - c-redis-data:/data
  elasticsearch:
    image: elasticsearch:latest
    container_name: ElasticSearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    volumes:
      - c-elastic-search-data:/usr/share/elasticsearch/data
volumes:
  c-redis-data:
  c-elastic-search-data: