version: "1.0"
services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: RabbitMQ
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  rabbitmq-data: