version: "1.0"
services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: MQ-RabbitMQ
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  kafka:
    image: apache/kafka:latest
    container_name: MQ-Kafka
    restart: always
    ports:
      - 9092:9092
volumes:
  rabbitmq-data: