version: "1.0"
services:
  postgres:
    image: postgres
    container_name: PostgreSql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qweQWE!
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: PgAdmin4
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kidrish.com
      PGADMIN_DEFAULT_PASSWORD: 123qweQWE!
    volumes:
      - pgadmin4-data:/var/lib/pgadmin

volumes:
  postgresql-data:
  pgadmin4-data: